export { default as Home } from "./Home/Home"
export { default as Blog } from "./Blog/Blog"
export { default as Contact } from "./Contact/Contact"
export { default as Features } from "./Features/Features"
export { default as Pricing } from "./Pricing/Pricing"